### ISSUE TITLE
Eliminate Random parameters

### ISSUE THREAD

**Issue by james-k-polk** [l0s/fernet-java8#164]
Misuse and misunderstanding of Java's Random and SecureRandom classes is a common source of security-critical mistakes. Forcing users to pass instances of Random does allow for things like repeatability for testing, but it also allows users to shoot themselves in the foot. On balance, I believe the right decision would be to eliminate them as parameters in such critical methods as Key.generateKey and Token.generate and perhaps others. Note that the [python cryptography module](https://cryptography.io/en/latest/fernet/)  does not require random parameters.

The correct behavior is for your library to manage Randoms by supplying a SecureRandom instance instantiated via the no-args constructor new SecureRandom().

**Comment by l0s** [comment]
Hi @james-k-polk, thanks for the feedback!

How would you feel about changing the parameters from `Random` to `SecureRandom`? That would have the same impact as users would not be able to supply the less secure implementation. I can also provide no-args variants which would be secure by default.

I do want to provide users the ability to supply custom entropy sources without giving them a foot gun. For example, some AWS users may want to use [KMS](https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateRandom.html) to seed their entropy source.

**Comment by james-k-polk** [comment]
That sounds like an excellent plan

**Comment by l0s** [comment]
@james-k-polk I have #165 open to replace `Random` with `SecureRandom`. I will bundle it with other breaking changes and then bump the minor revision number. I would like to hold off on introducing methods that use a default entropy source as I feel #13 will be the cleanest way to do that. Adding them directly to `Key` and `Token` will clutter the public interface and some might argue that `Token` already has too many methods.

**Comment by l0s** [comment]
@james-k-polk `Random` can no longer be used starting with version 1.4.0. I'll start experimenting with interfaces that eliminate the entropy parameter altogether in the scope of #13 .

**Comment by james-k-polk** [comment]
I suppose I disagree. I think it's best to have methods like Token.generate(Key, byte[]) that avoid the Random parameter altogether. I came to this issue from a question on Stackoverflow where a user who was familiar with the python fernet library from cryptography.io was frustrated that fernet-java was more complicated. From his point-of-view, an API with extra parameters actually made life worse. I would think the AWS scenario would be far more rare and that almost all users just need the library to use a SecureRandom instance gotten via `new SecureRandom();` under the hood without requiring any intervention on their part.

**Comment by l0s** [comment]
I see. I suppose it's not the end of the world to have slightly bloated public API to provide convenience methods. Taking a cue from the Java API, `Instant` has static methods to generate instances even though the `Clock` object is arguably the right way to generate them. In addition, `ThreadPoolExecutor` has four separate constructors to accommodate different levels of customisation.

I'll add the convenience methods. Since the change is backward compatible, I will not rev-bump.

**Comment by l0s** [comment]
@james-k-polk, version 1.4.1 adds the convenience methods.
