### ISSUE TITLE
Method visibility changes

### ISSUE THREAD

**Issue by aram-paronikyan-cognaize** [l0s/fernet-java8#190]
Hi,

I would suggest changing the visibility of some methods and constructors making them public. Examples below:
Method -> Token.fromBytes(final byte[] bytes)
Constructor ->  Key(final byte[] concatenatedKeys)

This would be good for those who work with bytes rather than strings. 
Basically, there is no need to extend these classes and changing the visibilities above should not break the code logic. 
Thank you!

**Comment by l0s** [comment]
@aram-paronikyan-cognaize thanks for submitting this issue. I agree, there is no harm in increasing the visibility of these methods. I'll create a PR to do this.

**Comment by l0s** [comment]
@aram-paronikyan-cognaize, version [1.4.2](https://github.com/l0s/fernet-java8/releases/tag/fernet-java-1.4.2) in Maven Central has this change.

**Comment by aram-paronikyan-cognaize** [comment]
@l0s thank you very much!
