### ISSUE TITLE
Fernet complementing or superseded by PASETO

### ISSUE THREAD

**Issue by dlehammer** [l0s/fernet-java8#194]
From the current [README](https://github.com/l0s/fernet-java8#why-fernet-why-not-jwt):

> ## Why Fernet, Why not JWT?
> 
> Valid concerns have been raised about the JWT specification:
> * [No Way, JOSE! Javascript Object Signing and Encryption is a Bad Standard That Everyone Should Avoid](https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid)

The "No Way, JOSE!.." (2017) post referenced above, has been updated with a link to the announcement "[Paseto is a Secure Alternative to the JOSE Standards (JWT, etc.)](https://paragonie.com/blog/2018/03/paseto-platform-agnostic-security-tokens-is-secure-alternative-jose-standards-jwt-etc)" (2018).

Now that [PASETO](https://paseto.io/) is officially supported, which is the more secure choice, Fernet or PASETO **?**

**Comment by l0s** [comment]
@dlehammer if you are in a position to choose (i.e. you are not integrating with systems that already use Fernet), you may want to go with PASETO. PASETO appears to have an active community and a [draft IETF RFC](https://www.ietf.org/archive/id/draft-paragon-paseto-rfc-00.txt).

**Comment by dlehammer** [comment]
@l0s Thank you for clarifying the current state, perhaps the README section should be updated to reflect that recommendation :)

**Comment by l0s** [comment]
@dlehammer it's probably best that I just remove that section from the README. The intention was not to enumerate or discuss all JWT alternatives nor was it meant to be a recommendation. I'll submit a change shortly.
