### ISSUE TITLE
Update dependencies to fix security vulnerabilities

### ISSUE THREAD

**Issue by sar009** [l0s/fernet-java8#962]
# Narratives
 The latest version of fernet-java8(1.5.0) seems to be released on Sep 26, 2020. Since then there have been a couple of security vulnerabilities reported. Please upgrade the dependent library versions. 

# Scenarios
N/A

# Technical Details
N/A

# Other Details
N/A

# Reference
* https://mvnrepository.com/artifact/com.macasaet.fernet/fernet-java8/1.5.0
* <img width="398" alt="image" src="https://github.com/l0s/fernet-java8/assets/3882922/4be78ffa-a85d-42e8-ba65-940efc84fc0c">

**Comment by l0s** [comment]
Is the concern specifically about the `fernet-java8` library? By design, it [does not have any dependencies](https://github.com/l0s/fernet-java8/blob/master/fernet-java8/pom.xml). The referenced CVEs are all test dependencies, which are not brought in if pulling the library from Maven.

**Comment by sar009** [comment]
oh okay...should the test dependencies be updated? the maven listing page paints a wrong picture

**Comment by l0s** [comment]
Yes, the Maven listing is misleading. The test dependencies are used when building the project from source. I've been keeping the dependencies fairly up-to-date, but that won't be reflected on Maven. The Snyk reports provide a more accurate view of the latest snapshot builds:
* [fernet-java8](https://snyk.io/test/github/l0s/fernet-java8?targetFile=pom.xml&tab=issues) (no dependencies)
* [fernet-jersey-auth](https://snyk.io/test/github/l0s/fernet-java8?targetFile=fernet-jersey-auth%2Fpom.xml&tab=dependencies)
* [fernet-aws-secrets-manager-rotator](https://snyk.io/test/github/l0s/fernet-java8?targetFile=fernet-aws-secrets-manager-rotator%2Fpom.xml&tab=dependencies)
